### ISSUE TITLE
Mixer output icons enlarged and pixelated

### ISSUE THREAD

**Issue by szszoke** [geoffreybennett/alsa-scarlett-gui#1]
Hello!

Finally this project is here :smile: 

Here is the first issue that I could find:

![image](https://user-images.githubusercontent.com/2766129/158081657-b0ee06a6-d754-45f6-8d58-619b2bc9e979.png)

The mixer output icons are enlarged and pixelated.

**Comment by geoffreybennett** [comment]
Finally indeed, and thanks for testing! Issue is fixed now.
