### ISSUE TITLE
Use `Esc` to close `View` windows

### ISSUE THREAD

**Issue by MagicLike** [geoffreybennett/alsa-scarlett-gui#102]
## Confirmation
- [x] I confirm that I have read the [FAQ](https://github.com/geoffreybennett/alsa-scarlett-gui/blob/master/FAQ.md).

## Issue Category
Please select the category that best describes your issue:
- [ ] Help Request
- [ ] Bug Report
- [x] Feature Request

## Issue Description
I think it would be convenient to be able to close the windows opened by the `View` menu - so `Routing`, `Mixer`, `Levels` & `Startup` - by pressing `Esc`.

**Comment by geoffreybennett** [comment]
Fixed in dev; please check.

**Comment by MagicLike** [comment]
> Fixed in dev; please check.

Works totally fine! :+1:
