### ISSUE TITLE
Lost default routing, cannot get direct monitoring working

### ISSUE THREAD

**Issue by the-arkhive** [geoffreybennett/alsa-scarlett-gui#106]
I feel a bit stupid for this actually, as I should have taken a screenshot of the default routing in the GUI. I got my scarlett solo gen 4 working, updated the firmware and such. I had been having an issue where my desktop audio output was being mixed back into the input from the interface. I incorrectly assumed there would be some way to return the routing back to it's default state, so I just cleared it all. That technically fixed the problem I was having, but now I cannot seem to get direct monitoring working again. I've read through the docs provided and cannot fully wrap my head around a lot of it. Most of the images that might also give some insight into routing are of much more complicated interfaces with more inputs and outputs, so while I have tried replicating some of the setups best I can on my hardware, I'm at a bit of a loss. It might also be worth noting that when I launch the GUI there is nothing in the 'Analogue Outputs' section.

If there is some way to restore default routing, or if you happen to have a setup that works for the solo 4th gen I'd really appreciate it!

EDIT: A bit more info that might be relevant. The 'Direct' button on the interface does not do anything (expected I assume since my routing is largely empty) and I've realized there are two destinations stacked on top of each other in the 'Hardware Outputs' section. One is 'Analogue 1' and the other is 'DSP Input 2 Capture Enum'. If I attempt to make a connection manually to 'Analogue 1' it instead connects to the 'DSP' output. The only way to get stereo output working is to use the preset, which means when I was trying to use the mixer options to mix my mic into my headphones I could not actually send the mix to 'Analogue 1'

**Comment by geoffreybennett** [comment]
Hi @the-arkhive,

Easy solution: run `scarlett2 reset-config`.

Longer answer: you're using the master branch of `alsa-scarlett-gui`, which does not (yet) support the 4th Gen. There is no way to fix the routing if you're using the code on the master branch. Please do `git checkout dev`, rebuild, and then things will work much much better (you'll even have a "Reset Configuration" option in the GUI :slightly_smiling_face:).

This answer will be out of date Real Soon Now. I've just about finished updating the documentation and then will merge everything from the dev branch into master.

Regards,
Geoffrey.

**Comment by geoffreybennett** [comment]
Hi again @the-arkhive,

I've released 0.4.0 which has Scarlett 4th Gen support, and the updated docs hopefully explain all the things for you.

Let me know how you go please!

Regards,
Geoffrey.

**Comment by the-arkhive** [comment]
Thanks so much!!! Everything seems to be working perfectly. Loving the new UI too!!

**Comment by the-arkhive** [comment]
Forgot to mark as closed. Oops
