### ISSUE TITLE
Virtual audio channels like in windows / macos

### ISSUE THREAD

**Issue by jeffreydereus** [geoffreybennett/alsa-scarlett-gui#115]
## Confirmation
- [x] I confirm that I have read the [FAQ](https://github.com/geoffreybennett/alsa-scarlett-gui/blob/master/FAQ.md).

## Issue Category
Please select the category that best describes your issue:
- [ ] Help Request
- [ ] Bug Report
- [x] Feature Request

## Environment Details
Please provide the following details about your environment.

### Linux Distribution and Version
- Distribution: Parrot Security
- Version: 6.0 (lorikeet)

### Kernel Version
- Kernel version: 6.5.0-13parrot1-amd64

### Focusrite Interface Series and Model
- Series: Scarlett 3rd gen
- Model: 18i8

### Audio System
- [x] PulseAudio
- [ ] JACK
- [ ] PipeWire

## Issue Description

In windows there's an option to "expose" all the available virtual channels to the windows sound control.
This way I'm able to select which virtual channel an application should output it's sound to. E.g spotify into "Scarlett 18i8 channel 7/8" and FL Studio into "scarlett 18i8 channel 5/6" which I can then route in the software to a specific hardware output into my behringer mixer.

It would be very helpful if this program got such an option as well.

**Comment by geoffreybennett** [comment]
Hi @jeffreydereus,

`alsa-scarlett-gui` only deals with controlling the settings on the interface itself, nothing to do with audio from the Linux application perspective (that's handled by ALSA/PulseAudio/JACK/PipeWire).

PulseAudio already has a facility to create virtual sound cards with the [Module Remap Sink](https://freedesktop.org/wiki/Software/PulseAudio/Documentation/User/Modules/#module-remap-sink) and module-remap-source modules.

Let me know if you need assistance with that and I'll write up an example.

Regards,
Geoffrey,

**Comment by jeffreydereus** [comment]
Hi @geoffreybennett,

Thanks for your reply! I couldb’t figure it out with the pulseAudio module and then realised that the scarlett software had something similar already, hence the question.

if you could write up an example that’d be super helpful!
Main part that I couldn’t figure out was giving the sink a name, for some reason it kept defaulting to “Null sink” or something like that and how to then link it to the configurable I/O in `alsa-scarlet-gui`

**Comment by yatli** [comment]
@jeffreydereus try `pipewire` -- it's awesome!
There's also `pipewire-pulseaudio`, `pipewire-jack` for compatibility with PA/JACK.

In an audio software, keep the default options (system / capture and system / playback). Here's I'm using Bitwig:
![image](https://github.com/geoffreybennett/alsa-scarlett-gui/assets/20684720/9a596541-8aae-4fd6-bbc2-845e20e39499)

Then, install `qpwgraph`, which is a patchbay for everything audio/midi:
![image](https://github.com/geoffreybennett/alsa-scarlett-gui/assets/20684720/f414f7c8-5600-45dd-b65f-59313a1ac804)

As you can see, Bitwig requested two audio inputs, and you can plug in whatever source available in your system, or add multiple connections so that pipewire will mix it for you:

![image](https://github.com/geoffreybennett/alsa-scarlett-gui/assets/20684720/4465edee-8a2c-48b6-9f07-15ba5e41e154)

^^ here, both the mic, and ADAT input 3/4 are mixed and sent to Bitwig.

**Comment by jeffreydereus** [comment]
@yatli 

Thanks for your suggestion! 

However for now I wanna try and get it working without installing any additional packages as my use case isn't quite for using it with any music creation programs.
I will keep it in mind though and might try it in a couple months.

**Comment by jeffreydereus** [comment]
@geoffreybennett 

Thanks! This seems to work, only issue I now have is that pulse audio doesn't save which applications made use of which virtual output.

Do you by chance have a solution to that as well?

**Comment by geoffreybennett** [comment]
Hi @jeffreydereus,

That's great news that the virtual outputs work!

Unfortunately I don't know why PA isn't remembering your output device selection. When I select a different output for an application in pavucontrol on the Playback tab, the selection is remembered. You might want to try asking in a forum for PulseAudio support, maybe start here: https://www.freedesktop.org/wiki/Software/PulseAudio/

Another thing you could try is setting the PULSE_SINK environment variable to select the output device as per https://www.freedesktop.org/wiki/Software/PulseAudio/FAQ/

Regards,
Geoffrey.

**Comment by geoffreybennett** [comment]
I also found this which (as I read it) says that the `stream-restore` module should just do what you want. Maybe you don't have that module loaded? Maybe you have the `restore_device=false` setting set? Maybe the software you're using selects the stream itself? Maybe the software you're using does something to make PA think it's a new stream, not the same stream as before?
https://www.freedesktop.org/wiki/Software/PulseAudio/Documentation/User/DefaultDevice/

**Comment by jeffreydereus** [comment]
@geoffreybennett 

Thanks for checking! I'll see if I can fix it with the links you provided.

Regards,
Jeffrey
