### ISSUE TITLE
FAQ Link Broken

### ISSUE THREAD

**Issue by F1LT3R** [geoffreybennett/alsa-scarlett-gui#116]
## Confirmation

- [X] I confirm that I have read the [FAQ](https://github.com/geoffreybennett/alsa-scarlett-gui/blob/master/FAQ.md).

## Issue Category

- [X] Bug Report

## Environment Details

GitHub

### Linux Distribution and Version

N/A

### Kernel Version

N/A

### Kernel Messages

N/A

### Focusrite Interface Series and Model

N/A

### Audio System

N/A
 
## Issue Description

Link to [Control Panel Installation Prerequisites — Linux Kernel](https://github.com/geoffreybennett/alsa-scarlett-gui/blob/master/INSTALL.md) is broken on the FAQ page:
https://github.com/geoffreybennett/alsa-scarlett-gui/blob/master/FAQ.md

![image](https://github.com/geoffreybennett/alsa-scarlett-gui/assets/1218446/4aaa6b13-b594-4015-86ba-bb46988c0250)

**Comment by geoffreybennett** [comment]
Thanks for the report; fixed now!
