### ISSUE TITLE
Feature request: command line parameters

### ISSUE THREAD

**Issue by alterNERDtive** [geoffreybennett/alsa-scarlett-gui#123]
## Confirmation

- [x] I confirm that I have read the [FAQ](https://github.com/geoffreybennett/alsa-scarlett-gui/blob/master/FAQ.md).

## Issue Category

- [ ] Help Request
- [ ] Bug Report
- [x] Feature Request

## Issue Description

I use a keyboard shortcut to mute my mic on the fly. Currently it mutes the Pipewire device(s).

It would be absolutely delightful if alsa-scarlett-gui had a command line parameter to mute the mic on the device directly, given that it already has a button for it in the GUI. E.g. `--toggle-mute` and/or `--mute [on|off]`, which would set the mute status and then exit. That way I would still get the visual feedback on the device, and it would also work for the phone input/output thingy.

Potentially you could even add more parameters to do other things as well.

If that’s completely out of scope for an application that literally has “gui” in its name, that’s fine. Figured it wouldn’t hurt to ask. Also, great piece of software! Definitely better than the official Windows thing 😬

**Comment by geoffreybennett** [comment]
Hi @alterNERDtive!

`alsa-scarlett-gui` is just a front-end to the kernel's ALSA controls, and there's already command line tools to get/set those. Have a look at this discussion for some ideas: https://github.com/geoffreybennett/alsa-scarlett-gui/discussions/119 and let me know if you need any assistance.

> Also, great piece of software! Definitely better than the official Windows thing 😬

Thank you :slightly_smiling_face:

Regards,
Geoffrey.

**Comment by alterNERDtive** [comment]
Great, I’ll have a look. Thanks!
