### ISSUE TITLE
Label in Level meters wrongly formatted or value is wrong.

### ISSUE THREAD

**Issue by Ka-zam** [geoffreybennett/alsa-scarlett-gui#126]
## Confirmation
- [x] I confirm that I have read the [FAQ](https://github.com/geoffreybennett/alsa-scarlett-gui/blob/master/FAQ.md).

## Issue Category
Please select the category that best describes your issue:
- [ ] Help Request
- [x] Bug Report
- [ ] Feature Request

### Linux Distribution and Version
```
DISTRIB_ID=Ubuntu
DISTRIB_RELEASE=24.04
DISTRIB_CODENAME=noble
DISTRIB_DESCRIPTION="Ubuntu 24.04 LTS"
```

### Kernel Version
```
6.8.0-36-generic
```

### Kernel Messages
```
[    1.534125] usb 5-1: New USB device strings: Mfr=1, Product=3, SerialNumber=2
[    1.534127] usb 5-1: Product: Scarlett 4i4 4th Gen
[    1.534129] usb 5-1: Manufacturer: Focusrite
[    1.534130] usb 5-1: SerialNumber: S4K9Z8C3802C64
[    6.355641] usb 5-1: Focusrite Scarlett Gen 4 Mixer Driver enabled (pid=0x821a); report any issues to https://github.com/geoffreybennett/scarlett-gen2/issues
[    6.357512] usb 5-1: Firmware version 2108
[    6.378837] usb 5-1: Quirk or no altset; falling back to MIDI 1.0
```
### Audio System
- [ ] PulseAudio
- [ ] JACK
- [x] PipeWire

## Issue Description
Text in Level meters seems to be wrong or wrongly formatted. Expected a string like "-3".

![Screenshot from 2024-07-02 09-43-14](https://github.com/geoffreybennett/alsa-scarlett-gui/assets/12671719/05432e0a-cc31-4f0c-a725-b49d40ff3c32)

**Comment by geoffreybennett** [comment]
Hi @Ka-zam,

Thanks for your report! Seems there is something different about the font selected by Ubuntu vs. Fedora. I've made an update and it works as expected now (at least for me!) on Ubuntu 23.10 and 24.04. Please try out either the new master or dev branches that I pushed & let me know!

Regards,
Geoffrey.

**Comment by Ka-zam** [comment]
@geoffreybennett  Works perfectly! 

Thank you!
