### ISSUE TITLE
Allow changing digital I/O mode on Focusrite 18i20 3rd Gen

### ISSUE THREAD

**Issue by napaalm** [geoffreybennett/alsa-scarlett-gui#129]
## Confirmation
I confirm that I have read the [FAQ](https://github.com/geoffreybennett/alsa-scarlett-gui/blob/master/FAQ.md).

## Issue Category
Feature Request

### Focusrite Interface Series and Model
- Series: Scarlett 3rd Gen
- Model: 18i20

## Issue Description
Focusrite Control has the ability to set the "Digital I/O Mode" of the interface, which basically allows to switch the optical in/out format from ADAT to S/PDIF. Would it be possible to implement this functionality?

For reference, here's the screenshot from the [manual](https://fael-downloads-prod.focusrite.com/customer/prod/s3fs-public/downloads/Scarlett%2018i20%203rd%20Gen%20User%20Guide_EN.pdf):

![2024-07-13-002901_726x1419_scrot](https://github.com/user-attachments/assets/d133d6e5-6f9c-42c1-aa77-836e9812b1e5)

**Comment by geoffreybennett** [comment]
Hi @napaalm,

I'm pleased to be able to report that this functionality is already implemented, although not in any released version yet.

To try it out now:
- Install Linux kernel 6.10 or use the [backported driver](https://github.com/geoffreybennett/scarlett-gen2/releases/tag/v6.9-v1.3)
- Build alsa-scarlett-gui from the master branch

Feedback would be very welcome!

See also https://github.com/geoffreybennett/scarlett-gen2/issues/9

Regards,
Geoffrey.

**Comment by napaalm** [comment]
Hello @geoffreybennett. Today I tested alsa-scarlett-gui 0.4.1 on Linux 6.11 and I confirm that I'm able to change the I/O mode to S/PDIF!
I think the issue can now be closed, thank you.

**Comment by geoffreybennett** [comment]
@napaalm Awesome, thank you for testing!

**Comment by geoffreybennett** [comment]
Hm, black on grey text is not a great look! But that's where the options should be. Can you attach the output of:
```
sudo dmesg | grep -A 5 -B 5 -i scarlett
uname -a
lsusb -d1235:
```
And attach the configuration saved by: `alsactl store X -f /tmp/scarlett.state` (replace `X` with the card number shown by `aplay -l`).

**Comment by caryatid** [comment]
Nothing to be sorry about -- you've done amazing work - and I have other workable setups.
