### ISSUE TITLE
Mixer broken

### ISSUE THREAD

**Issue by mannaris** [geoffreybennett/alsa-scarlett-gui#135]
# `alsa-scarlett-gui` Issue Template

Thank you for taking the time to contribute to the `alsa-scarlett-gui` project. Before you submit your issue, please ensure you have checked the FAQ and provide the necessary information below.

## Confirmation
- [x] I confirm that I have read the [FAQ](https://github.com/geoffreybennett/alsa-scarlett-gui/blob/master/FAQ.md).

## Issue Category
Please select the category that best describes your issue:
- [x] Help Request
- [ ] Bug Report
- [ ] Feature Request

## Environment Details
Please provide the following details about your environment.

### Linux Distribution and Version
(paste output from `cat /etc/redhat-release` or `cat /etc/lsb_release` here)
- Distribution: Fedora
- Version: 40

### Kernel Version
(paste output from `uname -r` here)
- Kernel version: 6.10.6-200.fc40.x86_64

### Kernel Messages
(paste output from `dmesg | grep -A 5 -B 5 -i focusrite` here)

[    2.452565] hub 2-1.4:1.0: 4 ports detected
[    2.477312] usb 1-2.3: new high-speed USB device number 5 using xhci_hcd
[    2.581334] usb 1-2.3: New USB device found, idVendor=1235, idProduct=8212, bcdDevice= 6.45
[    2.581340] usb 1-2.3: New USB device strings: Mfr=1, Product=3, SerialNumber=2
[    2.581343] usb 1-2.3: Product: Scarlett 4i4 USB
[    2.581345] usb 1-2.3: Manufacturer: Focusrite
[    2.581347] usb 1-2.3: SerialNumber: xxxxxxx
[    2.737698] usb 1-2.4: new high-speed USB device number 6 using xhci_hcd
[    2.846220] usb 1-2.4: New USB device found, idVendor=1b1c, idProduct=f10b, bcdDevice=93.11
[    2.846226] usb 1-2.4: New USB device strings: Mfr=1, Product=2, SerialNumber=0
[    2.846229] usb 1-2.4: Product: CORSAIR USB Hub
--
[   18.099679] VBoxNetAdp: Successfully started.
[   18.111799] nvidia-gpu 0000:0b:00.3: i2c timeout error e0000000
[   18.111805] ucsi_ccg 0-0008: i2c_transfer failed -110
[   18.111808] ucsi_ccg 0-0008: ucsi_ccg_init failed - -110
[   18.111812] ucsi_ccg 0-0008: probe with driver ucsi_ccg failed with error -110
[   18.452215] usb 1-2.3: Focusrite Scarlett Gen 3 Mixer Driver enabled (pid=0x8212); report any issues to https://github.com/geoffreybennett/scarlett-gen2/issues
[   18.475583] usb 1-2.3: Firmware version 1605
[   18.492819] usb 1-2.3: Quirk or no altset; falling back to MIDI 1.0
[   18.493404] usbcore: registered new interface driver snd-usb-audio
[   20.691203] igb 0000:07:00.0 enp7s0: igb: enp7s0 NIC Link is Up 1000 Mbps Full Duplex, Flow Control: RX
[   21.633249] wlp6s0: authenticate with 44:4e:6d:b3:a5:03 (local address=8e:39:7c:17:1c:d2)
--
[ 4576.778543] usb 1-2.3: USB disconnect, device number 5
[ 4694.215420] usb 1-2.3: new high-speed USB device number 12 using xhci_hcd
[ 4694.318744] usb 1-2.3: New USB device found, idVendor=1235, idProduct=8212, bcdDevice= 6.45
[ 4694.318754] usb 1-2.3: New USB device strings: Mfr=1, Product=3, SerialNumber=2
[ 4694.318759] usb 1-2.3: Product: Scarlett 4i4 USB
[ 4694.318763] usb 1-2.3: Manufacturer: Focusrite
[ 4694.318767] usb 1-2.3: SerialNumber: xxxxxxx
[ 4695.969202] usb 1-2.3: Focusrite Scarlett Gen 3 Mixer Driver enabled (pid=0x8212); report any issues to https://github.com/geoffreybennett/scarlett-gen2/issues
[ 4695.992566] usb 1-2.3: Firmware version 1605
[ 4696.011434] usb 1-2.3: Quirk or no altset; falling back to MIDI 1.0
[ 6124.764096] usb 1-2.3: Scarlett Gen 3 USB request result cmd 1001 was -71
[ 6124.766839] usb 1-2.3: USB disconnect, device number 12
[ 6206.369919] usb 1-2.3: new high-speed USB device number 13 using xhci_hcd
[ 6206.473368] usb 1-2.3: New USB device found, idVendor=1235, idProduct=8212, bcdDevice= 6.45
[ 6206.473378] usb 1-2.3: New USB device strings: Mfr=1, Product=3, SerialNumber=2
[ 6206.473382] usb 1-2.3: Product: Scarlett 4i4 USB
[ 6206.473386] usb 1-2.3: Manufacturer: Focusrite
[ 6206.473389] usb 1-2.3: SerialNumber: xxxxxxx
[ 6208.123809] usb 1-2.3: Focusrite Scarlett Gen 3 Mixer Driver enabled (pid=0x8212); report any issues to https://github.com/geoffreybennett/scarlett-gen2/issues
[ 6208.148151] usb 1-2.3: Firmware version 1605
[ 6208.165287] usb 1-2.3: Quirk or no altset; falling back to MIDI 1.0

### Focusrite Interface Series and Model
(maybe shown in kernel messages, or paste output from `lsusb -d1235:` if unsure)
- Series (e.g., Scarlett 2nd/3rd/4th Gen, Clarett USB, Clarett+): Scarlett 3rd Gen
- Model (e.g., Solo, 2i2, 4i4, etc.): 4i4

### Audio System
(use `ps aux | grep -E "pulseaudio|jackd|pipewire"` to check)
- [ ] PulseAudio
- [ ] JACK
- [x] PipeWire

## Issue Description
Please provide a detailed description of the issue or feature request, including steps to reproduce (if applicable), expected behavior, and actual behavior:

As soon as I switch the output in Fedora to the 4i4 the mixer stops working. If I reconnect I can hear my microphone on the headphone output as expected but as soon as I switch everything through the mixer just stops working. If I connect Sources and Sinks directly, without going through the mixer everything works as expected.

If I load the config on another Fedora 40 device with the same interface it works as expected.
Same kernel version, same Fedora version.

I'm sorry if this is something obvious, I'm relatively new to audio on linux and had the luxury that my old Windows config worked in standalone mode for nearly a year until it didn't.
![Screenshot from 2024-09-03 11-47-29](https://github.com/user-attachments/assets/3a4dac91-ba9e-43c6-9d5e-875e49d2d65b)

---

Thank you for helping improve `alsa-scarlett-gui`!

**Comment by geoffreybennett** [comment]
Hi @mannaris,

Thanks for including the screenshots. I see your sample rate is 192kHz, but the mixer in the Scarletts is disabled at that rate (hardware limitation). Switch to 48kHz and you should find that the mixer starts working again.

Regards,
Geoffrey.

**Comment by mannaris** [comment]
Ahh, ok. Do you perhaps know if I can specify the sample rate for different audio devices? I've set the 192kHz because my reciever does some weird stuff when it get's a higher sample rate that sounds better than with the default. So I kinda want the 192 for anything else than the focusrite and 48 for focusrite.
If this goes to much of topic I'm sorry, I'll figure it out.

Thank you for helping!

**Comment by geoffreybennett** [comment]
Not my field of expertise at all, but I found this: https://gitlab.freedesktop.org/pipewire/pipewire/-/issues/2883
which I think says you can set `audio.allowed-rates` on your receiver to 192kHz, and 48kHz for your Scarlett, and that will do what you want. :crossed_fingers:

**Comment by mannaris** [comment]
Works good enough :D Some applications lock into 192, but I can force it into 48 by playing a YouTube video and it'll stay locked as long as one application is still using it.

Thank you very much, I didn't expect to have a complete solution this fast.

**Comment by geoffreybennett** [comment]
I'm glad I could help! If you've got allowed-rates set to 48kHz for your Scarlett but pipewire sometimes uses 192kHz on it anyway, then I'd suggest opening an issue at https://gitlab.freedesktop.org/pipewire/pipewire/-/issues/
