### ISSUE TITLE
Build error for latest dev branch

### ISSUE THREAD

**Issue by MagicLike** [geoffreybennett/alsa-scarlett-gui#136]
# Build error for latest dev branch

## Confirmation
- [x] I confirm that I have read the [FAQ](https://github.com/geoffreybennett/alsa-scarlett-gui/blob/master/FAQ.md).

## Issue Category
Please select the category that best describes your issue:
- [ ] Help Request
- [x] Bug Report
- [ ] Feature Request

### Linux Distribution and Version
- Distribution: Ubuntu
- Version: 23.04

### Kernel Version
- Kernel version: 6.2.0-1007-lowlatency

## Issue Description
When running `make -j4` on the latest dev branch I get the following error:
```
make: *** No rule to make target 'img/alsa-scarlett-gui-logo.png', needed by 'alsa-scarlett-gui-resources.c'.  Stop.
```

**Comment by saxa** [comment]
Hi Itried to build it on my slackware64-current machine and all is building fine, with both options I tried with make -j4 or with meson/ninja. 
If you want to try the meson build then you can try my branch it is exactly same as the Geoffrey one but it has the meson.build system here https://github.com/saxa/alsa-scarlett-gui

**Comment by geoffreybennett** [comment]
@MagicLike Please try `make clean depclean` then `make -j4` & let me know if that helps.

**Comment by MagicLike** [comment]
> @MagicLike Please try `make clean depclean` then `make -j4` & let me know if that helps.

That worked! build and installation worked flawlessly!
