### ISSUE TITLE
Alsamixer shows almost nothing

### ISSUE THREAD

**Issue by scott8035** [geoffreybennett/alsa-scarlett-gui#14]
Hi again. I realize this issue probably should go with the kernel mod project, but that project doesn't accept issues, so here goes...

I'm using a 4i4 Gen3. According to everything I've read, including answers from Focusrite, these devices are USB-compliant and should present controls out-of-the-box. But when I fire up alsamixer, the only thing presented is the MSD Mode control, and I'm unable to change the value. Is this normal? How would I cause the many other controls to show up?

I'm running Linux Mint 20.3 with the customized kernel 5.15.12s1+ provided. Here's the output from `dmesg | grep -i -A 5 -B 5 scarlett`:

```
[    0.856221] amdgpu: hwmgr_sw_init smu backed is polaris10_smu
[    0.856259] [drm] Found UVD firmware Version: 1.130 Family ID: 16
[    0.856707] [drm] Found VCE firmware Version: 53.26 Binary ID: 3
[    0.905279] usb 3-3: New USB device found, idVendor=1235, idProduct=8212, bcdDevice= 6.04
[    0.905281] usb 3-3: New USB device strings: Mfr=1, Product=3, SerialNumber=2
[    0.905282] usb 3-3: Product: Scarlett 4i4 USB
[    0.905283] usb 3-3: Manufacturer: Focusrite
[    0.905283] usb 3-3: SerialNumber: D8Q97RJ198DE86
[    0.932409] [drm] Display Core initialized with v3.2.149!
[    0.942723] usb-storage 3-3:1.4: USB Mass Storage device detected
[    0.942806] scsi host10: usb-storage 3-3:1.4
--
[    1.434331] tsc: Refined TSC clocksource calibration: 4500.000 MHz
[    1.434339] clocksource: tsc: mask: 0xffffffffffffffff max_cycles: 0x40dd68c196e, max_idle_ns: 440795369676 ns
[    1.434360] clocksource: Switched to clocksource tsc
[    1.612442] ata5: SATA link down (SStatus 0 SControl 330)
[    1.924442] ata6: SATA link down (SStatus 0 SControl 330)
[    1.950656] scsi 10:0:0:0: Direct-Access     Scarlett Welcome Disk     0.10 PQ: 0 ANSI: 2
[    1.950744] sd 10:0:0:0: Attached scsi generic sg0 type 0
[    1.950957] sd 10:0:0:0: [sda] 384 512-byte logical blocks: (197 kB/192 KiB)
[    1.951075] sd 10:0:0:0: [sda] Write Protect is on
[    1.951076] sd 10:0:0:0: [sda] Mode Sense: 04 00 90 00
[    1.951193] sd 10:0:0:0: [sda] No Caching mode page found
--
[    9.846780] sd 10:0:0:0: ioctl_internal_command return code = 2
[    9.846782] sd 10:0:0:0: Sense Key : No Sense [current] 
[    9.846783] sd 10:0:0:0: Add. Sense: Medium not present
[   10.254350] random: crng init done
[   10.254352] random: 5 urandom warning(s) missed due to ratelimiting
[   10.875173] usb 3-3: Focusrite Scarlett Gen 2/3 Mixer Driver 5.15.12s1 enabled pid=0x8212
[   11.165055] usbcore: registered new interface driver snd-usb-audio
[   11.948936] snd_hda_intel 0000:09:00.1: IRQ timing workaround is activated for card #0. Suggest a bigger bdl_pos_adj.
[   12.598947] igb 0000:04:00.0 enp4s0: igb: enp4s0 NIC Link is Up 1000 Mbps Full Duplex, Flow Control: RX/TX
[   12.706632] IPv6: ADDRCONF(NETDEV_CHANGE): enp4s0: link becomes ready
[   15.846996] igb 0000:04:00.0 enp4s0: igb: enp4s0 NIC Link is Up 1000 Mbps Full Duplex, Flow Control: RX/TX
```

I wanted to make sure the unit was actually working before compiling this project. Thanks for any help you're able to provide.

---scott

**Comment by geoffreybennett** [comment]
Hi Scott, that's not quite right. Out of the box it is class-compliant but not all functionality is available and you need to disable MSD mode first. The Focusrite documentation and the USAGE.md here say this. If you've found somewhere else that says all controls are available out-of-the box, then that is wrong information.

To toggle the MSD control you can use this software. See https://github.com/geoffreybennett/alsa-scarlett-gui/blob/master/USAGE.md#msd-mass-storage-device-mode for a screenshot and explanation. You can also change the setting in alsamixer by pressing "M". So obvious, right?! That lack of a good UI is exactly why I created this project.

Regards,
Geoffrey.

**Comment by scott8035** [comment]
Thanks again, Geoffrey. Much appreciated. 

So many ports!
