### ISSUE TITLE
Unable to reset configuration on card hw:1: Invalid argument

### ISSUE THREAD

**Issue by FPB84** [geoffreybennett/alsa-scarlett-gui#145]
# `alsa-scarlett-gui` Issue Template

Thank you for taking the time to contribute to the `alsa-scarlett-gui` project. Before you submit your issue, please ensure you have checked the FAQ and provide the necessary information below.

## Confirmation
- [y] I confirm that I have read the [FAQ](https://github.com/geoffreybennett/alsa-scarlett-gui/blob/master/FAQ.md).

## Issue Category
Please select the category that best describes your issue:
- [y] Help Request
- [ ] Bug Report
- [ ] Feature Request

## Environment Details
Please provide the following details about your environment.

### Linux Distribution and Version
NAME="Pop!_OS"
VERSION="22.04 LTS"
ID=pop
ID_LIKE="ubuntu debian"
PRETTY_NAME="Pop!_OS 22.04 LTS"
VERSION_ID="22.04"
HOME_URL="https://pop.system76.com"
SUPPORT_URL="https://support.system76.com"
BUG_REPORT_URL="https://github.com/pop-os/pop/issues"
PRIVACY_POLICY_URL="https://system76.com/privacy"
VERSION_CODENAME=jammy
UBUNTU_CODENAME=jammy
LOGO=distributor-logo-pop-os

### Kernel Version
(paste output from `uname -r` here)
- Kernel version: 6.9.3-76060903-generic

### Kernel Messages
[  223.029915] usb 1-1: device descriptor read/64, error -71
[  223.719926] usb 1-1: new high-speed USB device number 12 using xhci_hcd
[  223.847408] usb 1-1: New USB device found, idVendor=1235, idProduct=821a, bcdDevice= 8.04
[  223.847412] usb 1-1: New USB device strings: Mfr=1, Product=3, SerialNumber=2
[  223.847413] usb 1-1: Product: Scarlett 4i4 4th Gen
[  223.847414] usb 1-1: Manufacturer: Focusrite
[  223.847415] usb 1-1: SerialNumber: S4GW6B93A821D9
[  225.495161] usb 1-1: Focusrite Scarlett Gen 4 Mixer Driver enabled (pid=0x821a); report any issues to https://github.com/geoffreybennett/scarlett-gen2/issues
[  225.495355] usb 1-1: Firmware version 2052
[  225.495931] usb 1-1: Focusrite Scarlett Gen 4 firmware version 2052 is too old; need 2089
[  225.496780] usb 1-1: Quirk or no altset; falling back to MIDI 1.0
[  236.748351] usb 1-1: Scarlett Gen 4 USB request result cmd 4004 was -71
[  297.412059] usb 1-1: Scarlett Gen 4 USB request result cmd 4002 was -110
[  304.987830] retire_capture_urb: 18 callbacks suppressed
[  320.658231] i915 0000:00:02.0: Using 39-bit DMA addresses
--
[  691.813400] usb 1-1: device descriptor read/64, error -71
[  692.908334] usb 1-1: new high-speed USB device number 17 using xhci_hcd
[  693.034816] usb 1-1: New USB device found, idVendor=1235, idProduct=821a, bcdDevice= 8.04
[  693.034819] usb 1-1: New USB device strings: Mfr=1, Product=3, SerialNumber=2
[  693.034820] usb 1-1: Product: Scarlett 4i4 4th Gen
[  693.034821] usb 1-1: Manufacturer: Focusrite
[  693.034822] usb 1-1: SerialNumber: S4GW6B93A821D9
[  694.679141] usb 1-1: Focusrite Scarlett Gen 4 Mixer Driver enabled (pid=0x821a); report any issues to https://github.com/geoffreybennett/scarlett-gen2/issues
[  694.679361] usb 1-1: Firmware version 2052
[  694.679965] usb 1-1: Focusrite Scarlett Gen 4 firmware version 2052 is too old; need 2089
[  694.680709] usb 1-1: Quirk or no altset; falling back to MIDI 1.0
[  703.077738] usb 1-1: Scarlett Gen 4 USB request result cmd 4004 was -71
[  875.459749] usb 1-1: Scarlett Gen 4 USB request result cmd 4002 was -110
[  959.962853] usb 1-1: Scarlett Gen 4 USB request result cmd 4002 was -71
[ 1277.581320] usb 1-1: Scarlett Gen 4 USB request result cmd 4002 was -71

### Focusrite Interface Series and Model
(maybe shown in kernel messages, or paste output from `lsusb -d1235:` if unsure)
- Series (e.g., Scarlett 2nd/3rd/4th Gen, Clarett USB, Clarett+): Scarlett 4th gen
- Model (e.g., Solo, 2i2, 4i4, etc.): 4i4

### Audio System
(use `ps aux | grep -E "pulseaudio|jackd|pipewire"` to check)
- [ ] PulseAudio
- [ ] JACK
- [y] PipeWire

## Issue Description
Please provide a detailed description of the issue or feature request, including steps to reproduce (if applicable), expected behavior, and actual behavior:
![Screenshot from 2024-10-17 14-49-36](https://github.com/user-attachments/assets/26bd9cd3-3a15-43fa-8728-98e66f22ae3c)
![Screenshot from 2024-10-17 14-50-00](https://github.com/user-attachments/assets/6fe43fa0-1dd1-4868-adcc-9ad21bf99eec)

Went through the installation, and installed the firmware, following the instructions given. When going to update firmware, I get the error message "Unable to reset configuration on card hw:1: Invalid argument" in terminal, or "Unable to reset configuration: Invalid argument" in the actual program itself. 

---

Thank you for helping improve `alsa-scarlett-gui`!

**Comment by geoffreybennett** [comment]
Hi @FPB84,

Did you manage this fix this yourself? Can you advise what you needed to do, in case someone else encounters the same problem?

Thanks,
Geoffrey.

**Comment by FPB84** [comment]
Hi, I apologize, if I knew what fixed it I would definitely put it here. Unfortunately I don’t. I had tried shutting off my pc and turning it back on to fix the issue several times and it didn’t work, however I got frustrated trying to solve the issue so I turned my pc off and went and took a nap and when I came back it worked fine. Honestly no clue what fixed the issue. Wish I could be more help!
