### ISSUE TITLE
My Scarlett 2i2 3rd Gen is not recognized

### ISSUE THREAD

**Issue by sim590** [geoffreybennett/alsa-scarlett-gui#148]
## Confirmation
- [x] I confirm that I have read the [FAQ](https://github.com/geoffreybennett/alsa-scarlett-gui/blob/master/FAQ.md).

## Issue Category
Please select the category that best describes your issue:
- [x] Help Request
- [ ] Bug Report
- [ ] Feature Request

## Environment Details
Please provide the following details about your environment.

### Linux Distribution and Version

```
DISTRIB_ID="Arch"
DISTRIB_RELEASE="rolling"
DISTRIB_DESCRIPTION="Arch Linux"
```

### Kernel Version

```
6.11.3-arch1-1
```

### Kernel Messages

```
sudo dmesg | grep -i -A 5 -B 5 focusrite
```

yields empty output. The only relevant output about my device that I get is the following:

```
[    8.507928] usb 1-1: Product: Scarlett 2i2 USB
[    8.507930] usb 1-1: Manufacturer: Scarlett 2i2 USB
```

### Focusrite Interface Series and Model

```
Bus 001 Device 002: ID 2f6e:4e17 Scarlett 2i2 USB Scarlett 2i2 USB
```

According to photos I saw on the Internet, it looks like a Scarlett Focusrite 2i2 3rd Gen. I bought it on Amazon. May be I got scammed?

### Audio System

- [ ] PulseAudio
- [ ] JACK
- [x] PipeWire

## Issue Description

I get the following screen when trying to launch the program:

![image](https://github.com/user-attachments/assets/e11b5def-489a-4655-a791-c042fb5520b3)

My kernel is younger than 6.7, so I should have default support?

I tried to disable MSD mode through the following manners:

* Holding the 48V button for 5 seconds while the device is powered
* Disconnecting the device, holding the 48V button, connecting the device and then wait for 5 seconds

I have no clue how to tell if MSD mode is disabled. Is it even relevant to my issue about my device not being recognized?

I also tried to look at `alsamixer` output and I only see the following:

![image](https://github.com/user-attachments/assets/1d57e030-5f22-429f-b321-14348ab448c7)

My pulemixer shows the following settings:

![image](https://github.com/user-attachments/assets/7e6cbce2-7e9a-4ea5-9e66-5094740fc224)

I have it set to `Pro Audio`. I have been using the device for more than a week, but I only get the audio through my PC from the left XLR port.

Here is a photo of my device:

![IMG_20241107_234724](https://github.com/user-attachments/assets/6111f652-5919-4894-b1b1-0b9e9d710f97)

---

Thank you for helping improve `alsa-scarlett-gui`!

**Comment by sim590** [comment]
If that can be useful, here's the output of `systool -vm snd_usb_audio`:

```
Module = "snd_usb_audio"

  Attributes:
    coresize            = "544768"
    initsize            = "0"
    initstate           = "live"
    refcnt              = "4"
    srcversion          = "33022587E5B32E6B7110218"
    taint               = ""
    uevent              = <store method only>

  Parameters:
    autoclock           = "Y"
    delayed_register    = "(null),(null),(null),(null),(null),(null),(null),(null),(null),(null),(null),(null),(null),(null),(null),(null),(null),(null),(null),(null),(null),(null),(null),(null),(null),(null),(null),(null),(null),(null),(null),(null)"
    device_setup        = "0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0"
    enable              = "Y,Y,Y,Y,Y,Y,Y,Y,Y,Y,Y,Y,Y,Y,Y,Y,Y,Y,Y,Y,Y,Y,Y,Y,Y,Y,Y,Y,Y,Y,Y,Y"
    id                  = "(null),(null),(null),(null),(null),(null),(null),(null),(null),(null),(null),(null),(null),(null),(null),(null),(null),(null),(null),(null),(null),(null),(null),(null),(null),(null),(null),(null),(null),(null),(null),(null)"
    ignore_ctl_error    = "N"
    implicit_fb         = "N,N,N,N,N,N,N,N,N,N,N,N,N,N,N,N,N,N,N,N,N,N,N,N,N,N,N,N,N,N,N,N"
    index               = "-1,-1,-1,-1,-1,-1,-1,-1,-1,-1,-1,-1,-1,-1,-1,-1,-1,-1,-1,-1,-1,-1,-1,-1,-1,-1,-1,-1,-1,-1,-1,-1"
    lowlatency          = "Y"
    midi2_enable        = "Y"
    midi2_ump_probe     = "Y"
    pid                 = "-1,-1,-1,-1,-1,-1,-1,-1,-1,-1,-1,-1,-1,-1,-1,-1,-1,-1,-1,-1,-1,-1,-1,-1,-1,-1,-1,-1,-1,-1,-1,-1"
    quirk_alias         = "(null),(null),(null),(null),(null),(null),(null),(null),(null),(null),(null),(null),(null),(null),(null),(null),(null),(null),(null),(null),(null),(null),(null),(null),(null),(null),(null),(null),(null),(null),(null),(null)"
    quirk_flags         = "0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0"
    skip_validation     = "N"
    use_vmalloc         = "Y"
    vid                 = "-1,-1,-1,-1,-1,-1,-1,-1,-1,-1,-1,-1,-1,-1,-1,-1,-1,-1,-1,-1,-1,-1,-1,-1,-1,-1,-1,-1,-1,-1,-1,-1"

  Sections:
  ```

**Comment by sim590** [comment]
I actually think that I was scammed and that I received a fake. I bought it here:

https://www.amazon.ca/Interface-g%C3%A9n%C3%A9ration-enregistrement-remplacement-linterface/dp/B0DCZ35VFQ/ref=sr_1_1_sspa?__mk_fr_CA=%C3%85M%C3%85%C5%BD%C3%95%C3%91&crid=FG9V25HKFMWW&dib=eyJ2IjoiMSJ9.nJJtn0bgYV7dkyEhsReqocWL0xE5PaUwNaexpP2uWV_NWq-YS_mwFN-_n3pHUI6-ywPVKUAYvSaISODUZmxU1_1mPCXfQArAfClanIbpfUwSqc7E43LSs2Luv1WPRuzyUwDdCINZkwwWolWZaGRKnXeQK8x1UEfAiBymCaiIzyQEaxdAgezGHveb17wl6qI1T4IScueWs4y-0wx0g6NXp0RDMmJTFsmnc8tbLClF3FpxhP82PMgwqLYj0ZmWakfI6uXgmCdclwiKmLVHkv8kJ6nw3lHC0kSZr9n2D1f9EtQ.T4_9sPAtZ6LM5OVxMw_keHT3aMUuNlxB5jZkNKjPy-M&dib_tag=se&keywords=Focusrite+Scarlett+2i2&qid=1731045378&s=musical-instruments&sprefix=focusrite+scarlett+2i2%2Cmi%2C90&sr=1-1-spons&sp_csd=d2lkZ2V0TmFtZT1zcF9hdGY&psc=1

sold by a chinese company. Am I mistaken?

**Comment by geoffreybennett** [comment]
Yeah, sorry, that's not a Focusrite interface. The USB vendor ID is wrong, and the mic jack doesn't look the same. Please report it to Amazon & Focusrite.

**Comment by sim590** [comment]
Alright. I did report this issue to both Amazon et Focusrite. I'm presently returning the unit and getting my refund. Thanks.
