### ISSUE TITLE
Icon and application name in task switcher/dock

### ISSUE THREAD

**Issue by szszoke** [geoffreybennett/alsa-scarlett-gui#2]
The application currently doesn't have an icon and the name that shows up in Gnome Dock is the Gtk App Id.

![image](https://user-images.githubusercontent.com/2766129/158082050-8c2a5019-849e-4650-9635-1b387946f39c.png)

Would this be resolved with a `.desktop` entry?

**Comment by geoffreybennett** [comment]
I couldn't figure this out before I gave up and released the code. I created icons (in the `src/img` directory) and had some success with putting them in `/usr/share/icons/hicolor/48x48/apps` (renamed to `alsa-scarlett-gui.png`) and running `gtk-update-icon-cache /usr/share/icons/hicolor`, but the icon still didn't display in the gnome top bar. Let me know if you figure it out!

**Comment by szszoke** [comment]
I managed to get it working!

You need to create a `.desktop` file that has the same name as the application ID.

Here are the contents of mine (replace `Exec` path with the correct path on your system)
```ini
[Desktop Entry]
Encoding=UTF-8
Value=1.5
Type=Application
Name=ALSA Scarlett Control Panel
Icon=alsa-scarlett-gui-256
Exec=/path/to/alsa-scarlett-gui/alsa-scarlett-gui
Categories=Utility
```
You also need to copy `alsa-scarlett-gui-256.png` to `/usr/share/pixmaps`.

I saved the file to `~/.local/share/applications` as `vu.b4.alsa-scarlett-gui.desktop`.

The desktop file needs to be in `/usr/share/applications` for a system-wide installation.

**Comment by szszoke** [comment]
It seems that with the `.desktop` file in place, the icon and application name will be shown correctly regardless how the binary is started.

You can probably remove the call to `gtk_window_set_default_icon_name` from `main.c`.

**Comment by geoffreybennett** [comment]
Thanks for figuring that one out @szszoke! I've created a branch named "desktop" which has hopefully all the necessary changes. If it doesn't build, do `make depclean` first to clear the dependencies (needed due to renamed file).

**Comment by szszoke** [comment]
Seems to be working for me:
```sh
make depclean
make
sudo make install
```

After things have been considered final, we could add some helpers to generate packages for different distributions.

I have done it before via Docker as a sort of "one click packaging" solution. I used the `debian` and `arch` images to generate `DEB` and `AUR` packages.
