### ISSUE TITLE
Exposing analog inputs + loopback to pulseaudio's audio inputs

### ISSUE THREAD

**Issue by AskAlice** [geoffreybennett/alsa-scarlett-gui#22]
How would this be done? Is there a way to do it in the gui?

**Comment by scott8035** [comment]
If I understand you correctly, then you don't do it with this application at all. If you install the pulseaudio-jack and/or pulseaudio-alsa packages (that's what they're called on Arch-like systems), then there will be a bridge between pulse and the respective sound system. Here's a picture that explains it better...

![Screenshot from 2022-05-25 20-57-58](https://user-images.githubusercontent.com/4405585/170399726-908bbf30-3b67-4b8e-9026-40cc1902cb29.png)

In that picture you can see the hardware that ALSA is managing, it's got six inputs and four outputs. The two boxes in the middle are created by the bridge package mentioned above, and you just wire them together via drag-n-drop. FYI, that screenshot is of a package called Catia, which you can get at kx.studio and elsewhere.

I hope I was aiming at the right target here...

**Comment by geoffreybennett** [comment]
> How would this be done? Is there a way to do it in the gui?

Hi Alice,

In the GUI, open the Routing window and select Presets → Direct (watch the animation at https://github.com/geoffreybennett/alsa-scarlett-gui to see an example). That will connect the hardware inputs to the PCM inputs. The PCM inputs are what ALSA sees, which is therefore what JACK or PulseAudio or PipeWire gets.

Focusrite call the last two PCM inputs "loopback" inputs, but that is actually a restriction in their software. You can actually use any PCM input for any purpose (hardware, mixer, or PCM source). This GUI exposes the full functionality of the hardware and any/all of the PCM inputs can be arbitrarily connected to any source.

Let me know if you've got more questions or if the above doesn't make sense.

Regards,
Geoffrey.
