### ISSUE TITLE
Include 2i4

### ISSUE THREAD

**Issue by LeePorte** [geoffreybennett/alsa-scarlett-gui#24]
Hi,

Would it be possible to include the 2i4 in your work?

The output from lsusb is `ID 1235:8200 Focusrite-Novation Scarlett 2i4 USB`

Cheers

**Comment by geoffreybennett** [comment]
Hi Lee,

No, that's not possible. According to Focusrite, the 1st and 2nd Gen Solo, 2i2, and 2i4 devices have no software-based controls, so this project is irrelevant to that device: https://support.focusrite.com/hc/en-gb/articles/207547145-Does-my-bus-powered-Scarlett-Solo-2i2-2i4-4i4-require-Scarlett-MixControl-or-Focusrite-Control-

Regards,
Geoffrey.
