### ISSUE TITLE
other repo has No issues Tab

### ISSUE THREAD

**Issue by juanpc2018** [geoffreybennett/alsa-scarlett-gui#27]
https://github.com/geoffreybennett/scarlett-gen2/releases

$ lsusb
Bus 001 Device 012: ID 1235:8208 Focusrite-Novation Clarett 8Pre USB

Clarett 8Pre USB,
its similar to 18i20mk3,
has Air on every Input,

Air its a small coil in-circuit, similar to ASP800 HMX 
Air was introduced in the Focusrite rackmount Channel Strips,
but with a real coil.

its like a passive high frequency shelf Eq, different coils, different feedback create different boost or cut.

Clarett 8Pre and 18i20 mk3 Air its an Emulated Coil, using a Capacitor & Op-Amp, like most modern Analog EQs,
Eqs with real coils are rare, specially for low frequency, requires a very dense "small AWG 44" ferrite core, high Henrry value, 40H.

different core "ferrite, iron, cobal, nickel", different harmonics, different saturation characteristics, etc...

Anyway....
8Pre USB has Air
18i20mk2 does Not.

8Pro Usb allows to convert ADAT input to TOSLINK for Clock Input, 
but usually is better to use a real s/pdif as clock source.
BNC is Clock Out Only.

most s/pdif PLL circuits are forgiving / lose, Not strict, because the lower voltage vs. AES/EBU, 
that allows a better clock to affect more the internal of the interface.
Dominate more, Enslave More.
but requires a good cable, with good copper, good double layer shielding minimum, proper dielectric insulator, etc...
for 192Khz silver is better.

8Pre USB also has LED VU Meter Output 1&2 + 1-8 Input.
18i20mk2 does Not, only 1-8 Input LED Vu Meter.

Output 1&2 have relays,
3-10 does Not.
Outout 1&2 has latest Cirrus Logic DAC, with low latency, much faster than older 192Khz DACs in Apogee Rosetta 192 for example.
Output 3-8 has latest AKM.

different reference audio.
Cirrus has more Circuit Lag / Spline in the Analog audio signal reconstruction,
AKM is more True to Digital reconstruction.

The main difference are the Analog Circuits,
18i20mk2 capacitors are very low end, crap.
8pre usb has very high quality Audio capacitors, with ultra low impedance.
sound is more clear and transparent.

internal clock is a bit different, but similar PLL type.

**Comment by geoffreybennett** [comment]
This is interesting information, but unrelated to this project I think. This project is a Linux GUI for the Scarlett Gen 2/3 range. There is no support for any Clarett interface either in the GUI or in the Linux ALSA mixer kernel driver, although:
1) I believe they're class-compliant, so audio should work fine
2) if (1) is true and someone wants to send me a 2Pre, 4Pre, and/or 8Pre USB interface then I will probably be able to add mixer support

**Comment by juanpc2018** [comment]
#1. 
USB Audio works ok, just has a minor problem with pulseaudio configuration file,
is set default to forced 44.1khz, and cannot change, 
should be auto,
creates problems with files played at 48khz, 88.20khz, 96khz, etc...
pulseaudio sample rate converter does Not work upwards, only downwards. 
easy to solve...

#2. 
i can donate ~0.326 XMR
something like ~$50usd. it was $75usd. a few months ago.
give me your xmr address or paste here the qr code,jpg
for safety: connect only to miner servers or private node server >200GB
like:
node.supportxmr.com:18081

#3.
Many people are selling the Clarett 8Pre USB to buy the New Clarett+ 8Pre USB with latest Cirrus and AKM ICs.
maybe different capacitors.
havent heard or seen inside to know exactly..

**Comment by geoffreybennett** [comment]
(1) I would not use PulseAudio anymore. Pipewire works so much better, and caters for both desktop and pro-audio work. Although do note that audio functionality is not in scope of this project. The Scarlett devices are USB audio class-compliant so no driver is needed for PCM audio. This GUI & the Scarlett ALSA mixer driver are only for controlling the proprietary features like the mixer.
(2) I'm not taking donations by cryptocurrency sorry.
(3) I am curious if they are the same functionality and same USB ID, with hardware differences that are not visible to software.

**Comment by geoffreybennett** [comment]
In case someone comes across this later, there is now support for the Clarett+ 8Pre here: https://github.com/geoffreybennett/scarlett-gen2/commits/scarlett-gen3
Clarett 8Pre USB support might be there too (it's currently untested).
