### ISSUE TITLE
Will this run on Arch Linux?

### ISSUE THREAD

**Issue by Chipwingg** [geoffreybennett/alsa-scarlett-gui#35]
This isn't an issue, more a question. 
As long as dependencies are there, will this work with arch? I am not an arch user yet, but I'm considering leaving my Ubuntu Studio for arch. (I had music people tell me it was better for latency). If this GUI doesn't work on arch, I may not make the decision to switch because I like this a lot.

**Comment by scott8035** [comment]
This is off-topic, but you could probably resolve any latency problems by just using the Liquorix kernel from https://liquorix.net/ instead of switching distros.

**Comment by saxa** [comment]
It surewly will work it works on my Slackware :)

**Comment by Chipwingg** [comment]
> This is off-topic, but you could probably resolve any latency problems by just using the Liquorix kernel from https://liquorix.net/ instead of switching distros.

I am looking at how this compares to my current ubuntu lowlatency kernel.... Thanks!

**Comment by geoffreybennett** [comment]
If you have the dependencies (like Gtk 4), then there's no reason this shouldn't work on Arch.
