### ISSUE TITLE
Scaling on 4K monitor is not respected

### ISSUE THREAD

**Issue by gaydenko** [geoffreybennett/alsa-scarlett-gui#37]
Hi! Thanks for the app!

I use KDE with 4K monitor scaled to 200%. For some reason the app seems to ignore the scaling. But it ignores it own way: it seems to be 2x scaled up instead of as some rare old apps (say, jaaa) scale 2x down.
I have attached a screenshot with Konsole on the background to estimate valid scaling.

Version 0.2 from Manjaro repo is used.

![alsa-scarlett-gui-01](https://user-images.githubusercontent.com/3740016/190848662-2a26242e-fe49-4ce1-aa26-699c792212d5.png)

**Comment by gaydenko** [comment]
Also have tried git version with the same result.

**Comment by Burtan** [comment]
Works for me debian testing (trixie) and 0.3.3

**Comment by gaydenko** [comment]
Yes, it does for me also now.
