### ISSUE TITLE
Small UI tweaks

### ISSUE THREAD

**Issue by szszoke** [geoffreybennett/alsa-scarlett-gui#4]
I experimented with a few very minor UI tweaks in the Router window.

I made the source/destination ports have the same width, added some padding and some border radius.

I also set the text labels to expand and to be aligned left/right depending on which side of the window they appear.

These changes are only really visible when you hover over a port, but they made the UI look cleaner to my eyes.

When the cursor moves over a port now, the highlighted area goes near the edge of the window, regardless of the length of the label.

I am not sitting at my computer now but I was thinking that at I can get the conversation going.

I will upload a screenshot later today or tomorrow.

I realize that small UI tweaks like the ones above could be highly personal but I'm still curious of you want to throw around ideas.

I will be using this application a lot moving forward and I also feel comfortable making changes in the source code to test out ideas.

**Comment by szszoke** [comment]
### Before
![image](https://user-images.githubusercontent.com/2766129/158255229-502549e5-ff94-48b6-b2f0-d6e29bf0fc82.png)

### After
![image](https://user-images.githubusercontent.com/2766129/158254974-7aaa616a-0dcb-43eb-b150-3bd66e1f65a1.png)

**Comment by geoffreybennett** [comment]
Thanks! Looks good to me! Send through a pull request?

**Comment by szszoke** [comment]
I will do that but it needs some more work. I just set the ports to have a static minimum width. It would be better if I could make them have the same width as the widest one without hardcoding numbers.
