### ISSUE TITLE
No sound on headphones

### ISSUE THREAD

**Issue by jsanta** [geoffreybennett/alsa-scarlett-gui#40]
Hi. Nice work you've done here, I can finally use my 18i8 3rd gen in Linux.

Just struggling with the following, made a simple routing in order to use some inputs and get the sound through the audio monitors.
That works pretty well, but I have no sound on the headphones (both 1 or 2 are silent). Opened alsamixer and could enable them manually. The thing is alsa mixer ruins the  routing done with the app.

Now I loaded my saved state (for this particular routing) and tried opening alsamixer to enable  the headphones. I can see them in  alsamixer but cannot adjust the volume (arrows don´t work).
Is there any way of enabling the headphones output through the Scarlet Gui app?

Hope you can  enlighten me, 'cause this frustrates me a bit.

**Comment by jsanta** [comment]
@szszoke Thanks! You're a life saver (not really that my life was depending on my headphones :P ) .
Had to read a bit and tried the direct Routing preset to make a test & fail detection of which channel was going to the Headphone output 1.

Ended up with this configuration:
![main screen](https://lh3.googleusercontent.com/drive-viewer/AJc5JmTCBO9m1ua3kTcRqp9M7O52-Kw8-erLrhJqSN8wTG9lvEob_dEhWBJEjBsZOJuLmAaiQ4Dy1ow=w1575-h894)

![routing](https://lh3.googleusercontent.com/drive-viewer/AJc5JmSIRMq8rvME_CNV8H7XWwIK6JQ7jDaWAn1oRAz76qAqrGefj69KSqkMuQ7pER8HGQMVs7WrMKk=w1575-h894)

I have some other routings there and  most certain that there's an extra unnecessary connection.
Hope this helps someone else.
Best regards and stay safe.

**Comment by mark-gunner** [comment]
For anyone looking and going "hang on the second headphone output is still silent"; do exactly the same as above only connect to Analogue 7/8.
