### ISSUE TITLE
gtk4 4.10 deprecates many functions; `-Werror` causes build failures

### ISSUE THREAD

**Issue by fenugrec** [geoffreybennett/alsa-scarlett-gui#50]
For example,

```
file.c: In function ‘add_state_filter’:
file.c:65:3: error: ‘gtk_file_chooser_add_filter’ is deprecated [-Werror=deprecated-declarations]
   65 |   gtk_file_chooser_add_filter(GTK_FILE_CHOOSER(native), filter);
```
According to https://docs.gtk.org/gtk4/class.FileChooserNative.html , this is deprecated since 4.10 which is fairly recent anyway.

I suggest modifying the Makefile to remove the `-Werror` flag - I can patch that when packaging at my end, but perhaps should be addressed here too.

cmake build configurations can help with this : a debug build can enable -Werror where it is useful, and a quieter release build that makes it easier / for packagers. Is there any interest in moving beyond plain makefiles to something else - cmake or other ?

**Comment by antode** [comment]
If someone can't build binary and looking for workaround, try to:
- open Makefile in editor /%repo_containing_dir%/alsa-scarlett-gui/src/Makefile, e.g.
  ```shell
  [ontosh@fedora ~]$ nano ~/tools/alsa-scarlett-gui/src/Makefile
  ```
- add new line after 
  ```Makefile
  CFLAGS += -DVERSION=\"$(VERSION)\"
  ```
- and paste following expression:
  ```Makefile
  CFLAGS += -Wno-error=deprecated-declarations
  ```
- run `make -j4`

**Comment by saxa** [comment]
Hi, AFAIK meson is the way for most of the gtk/gnome apps. I think its also simple and easy to use and a well stabilized project. https://mesonbuild.com/
