### ISSUE TITLE
Mixer no longer works when Jack is running

### ISSUE THREAD

**Issue by lkamp** [geoffreybennett/alsa-scarlett-gui#52]
I have a Scarlett 18i20 3rd Generation, and alsa-scarlett-gui works like a charm when using PulseAudio for audio input and output.

However, I have noticed that the mixer of my 18i20 doesn't work with Jack. Normally, I route analog inputs 1 and 2 and PCM outputs 1 and 2 to the mixer, and then from the mixer to analog outputs 1 and 2 (see screenshot).

But when Jack is running, there is no output on outputs 1 and 2. When I connect PCM 1 and 2 directly to the outputs in the routing, everything works. So it seems that Jack somehow mangles the internal routing of my 18i20 but the GUI doesn't notice the change.

Any ideas would be greatly appreciated!

![routing](https://github.com/geoffreybennett/alsa-scarlett-gui/assets/6946258/0fbadacb-0e75-4872-aead-4afeb54e211b)

**Comment by geoffreybennett** [comment]
Check that you're not using a sample rate over 48kHz. The Scarlett hardware mixer doesn't operate above 48kHz.
