### ISSUE TITLE
Is Clarett+ 4PRE supported?

### ISSUE THREAD

**Issue by blueberry** [geoffreybennett/alsa-scarlett-gui#59]
I see that there's Clarett+ 8PRE mentioned in the readme. It is not clear whether that's due to historical reasons (maybe other Clarett+ devices weren't available at the time), or Clarett+ models other than 8PRE are explicitly not supported?

**Comment by geoffreybennett** [comment]
Hi Blueberry,

The only Clarett+ model that is currently supported is the 8Pre. Support for the 2Pre and 4Pre needs to be done by someone who has one of those devices.

Regards,
Geoffrey.

**Comment by blueberry** [comment]
I have a Clarett+ 4PRE, but chronically lack time :) How is the support added (by me, supposedly)? Is it a matter of discovering the right configuration and punching it in, or I'd need to update my C chops and do some considerable low-level programming with alsa or whatever is relevant?

**Comment by geoffreybennett** [comment]
Hi Blueberry,

The 4Pre is mostly a subset of the 8Pre, so adding support isn't as much about diving deep into C coding as it is about becoming really familiar with every feature and all the relevant internal specifications of the device. The main task would involve reading USB traces from the Focusrite Control software. From this information, you'd determine the appropriate values to input into a new `struct scarlett2_device_info clarett_4pre_info` in the code [here](https://github.com/geoffreybennett/scarlett-gen2/blob/scarlett-gen3/sound/usb/mixer_scarlett_gen2.c) to mirror what Focusrite Control does.

While I do hope to support the 4Pre (and 2Pre) eventually, my current commitment is to the 3x Gen 4 interfaces that were just released and the 2x Vocaster interfaces. As you can imagine, supporting all these devices does come with its costs. I've set up a [fundraiser](https://gofund.me/71f94a9c) to help with this. If it garners enough support, I'll be in a position to add support for the 4Pre and 2Pre myself sooner.

Regards,
Geoffrey.

**Comment by zeiktuvai** [comment]
@geoffreybennett If I sent you the money to buy a 4pre would that help?  I just got one and would really like to not have to return it for a scarlett interface but I also no nothing about examining USB communication.

**Comment by geoffreybennett** [comment]
Hi @zeiktuvai,

Wow, that's an incredibly generous offer, thank you! If you're truly comfortable with providing the funds for a 4Pre, it would mean I could buy one right away and get the Linux support done quickly. They're in-stock locally for AUD$990, however they will usually price-match other Australian stores, and I see it elsewhere for AUD$899.

Please ensure this is a decision you're completely comfortable with. Your desire to support the community and this project is deeply appreciated. If you'd like to proceed, you can use the fundraiser link above & put a note that it is for the 4Pre support.

Best Regards,
Geoffrey.

**Comment by geoffreybennett** [comment]
@zeiktuvai I see your message in the linuxmusicians forum. Please read my reply there too.

**Comment by zeiktuvai** [comment]
@geoffreybennett I responded to you on linuxmusicians, will get it to you next pay check.

**Comment by geoffreybennett** [comment]
@zeiktuvai please email me: g@b4.vu. I will have something for you very soon.

**Comment by geoffreybennett** [comment]
All Clarett USB and Clarett+ models are supported now in alsa-scarlett-gui. Kernel support has been submitted upstream and should appear in 6.7.

**Comment by perfect7gentleman** [comment]
```
[    3.756883] usb 2-10: Product: Clarett+ 2Pre
[    7.336231] usb 2-10: Focusrite Clarett+ Mixer Driver enabled (pid=0x820a); report any issues to g@b4.vu
```

**Comment by geoffreybennett** [comment]
Confirmed, support is arriving in Linux 6.7. Source here if you want to use it before then: https://github.com/geoffreybennett/scarlett-gen2/releases/tag/v6.5.11c1
