### ISSUE TITLE
Output gain of ADAT channels

### ISSUE THREAD

**Issue by szszoke** [geoffreybennett/alsa-scarlett-gui#6]
I am using a second 18i20 that is configured to route physical ports to/from the ADAT channels.

In that setup the ADAT outputs of my `leader` device are effectively routed to the physical output of my `follower` device.

It would be nice to be able to set the gain for them the same way I can set the gain for the physical outputs on the `leader` device.

The `follower` is not connected to the computer. It is connected to the `leader` via TOSLink cables and configured to synchronize it's clock to the ADAT clock.

Having the `follower` connected would be impractical because then two 18i20 devices would show up on my system.

I realize this might not be useful for everyone so a goon approach would be to hide them initially and let the user chose if they should be shown or not.

**Comment by geoffreybennett** [comment]
Sorry, as far as I know, the Scarlett hardware does not support adjusting the signal level of the digital outputs. At best, you can work around this by sending the outputs through the internal mixer and using the mixer controls.

The Focusrite Control Scarlett 3rd Gen User Guide says:
![image](https://user-images.githubusercontent.com/1866657/158786210-e25cd189-f0f8-4b44-b18a-4b903f14cb86.png)

Other alternative is to connect `follower` to your computer and ignore the additional audio ports it presents. I did try making `alsa-scarlett-gui` work okay with multiple devices connected, although if they are identical devices they could be hard to distinguish (this is probably fixable). Also, pipewire is meant to work well with multiple audio interfaces.

**Comment by szszoke** [comment]
You are right that PW would work well, the problem is that I would get two "half" sound cards with their other half being just useless clutter. Using the internal mixer will have to do. Otherwise maybe here would be a way to only expose the mixer controls of a Focusrite card, could this be done in the driver?

**Comment by geoffreybennett** [comment]
I'm not sure, sorry. That'd be a question for the ALSA developers. My driver hooks into `snd_usb_mixer_apply_create_quirk()` in `sound/usb/mixer_quirks.c` and is completely independent from the PCM streaming side of things. I followed through the startup code in that directory and if you want to try, I'd look at not calling `snd_usb_create_streams()` in `card.c`.

**Comment by szszoke** [comment]
I will try to see if I have enough channels left in the mixer first.

Thanks for the tip!
