### ISSUE TITLE
FYI: alsa-scarlett-gui on Linux Mint Mate

### ISSUE THREAD

**Issue by Sonophoto** [geoffreybennett/alsa-scarlett-gui#64]
Just a comment, no action required Geoffrey.

I worked at building this on Linux Mint 20.3 but after spending 3 hours trying to meet all of the dependencies for GTK4 I got annoyed and gave up. Mint doesn't have GTK4 in its repos and apparently have no plans to do so...

Thanks for your efforts, I'm sure its a great tool! :smiley:

**Comment by geoffreybennett** [comment]
Yeah, I certainly wouldn't recommend trying it on Mint 20.3, or anything that doesn't have already have GTK4. It works on Mint 21.2 though:
![image](https://github.com/geoffreybennett/alsa-scarlett-gui/assets/1866657/065fb0ca-08c0-4ffa-9541-8485902f3c9b)
