### ISSUE TITLE
Running on Raspberry PI with PatchboxOS (blokas.io)

### ISSUE THREAD

**Issue by ralfcoenen** [geoffreybennett/alsa-scarlett-gui#69]
Iwas trying to get this nice mixer running on PatchboxOS on my Raspi, but unfortunately there is no gtk-4 in the repos for this. Flatpak also is no option, because it isn't in the repos either.

Any Ideas?

Thanks

**Comment by geoffreybennett** [comment]
Sorry, I don't know :(. Maybe ask PatchboxOS people if there's some way to get Gtk4 or Flatpak apps onto it?

**Comment by geoffreybennett** [comment]
Sorry, I don't think we can do anything with this. This is a Gtk4 app, so if there's no way to get Gtk4 libraries on a device, I don't think that device can run this app.
