### ISSUE TITLE
Supported devices does not list any Clarett models

### ISSUE THREAD

**Issue by 71GA** [geoffreybennett/alsa-scarlett-gui#72]
I compiled the binary v 3.1 and ran it. In the main menu I select <kbd>help</kbd> / <kbd>supported hardware</kbd> and there is no tab for Clarett devices. It would really be nice if that was added so that it does not contradict the statement ([link](https://github.com/geoffreybennett/alsa-scarlett-gui/blob/master/README.md?plain=1#L22-L23)) that Clarett devices are supported. :)

**Comment by fenugrec** [comment]
should be a simple matter of adding a few elements in `src/window-hardware.c`

**Comment by geoffreybennett** [comment]
Thanks, done!

**Comment by fenugrec** [comment]
I was going to make a PR for this, good thing I checked back before starting : )
