### ISSUE TITLE
4i4 gen3 : routing not working as expected

### ISSUE THREAD

**Issue by fenugrec** [geoffreybennett/alsa-scarlett-gui#74]
(kernel 6.6.1 , archlinux)

1- apply signal on channel 1
2- route to different Mixer Inputs
3- mixer window shows proper names
4- level meters don't make sense to me, seems like they totally ignore the routing, *or* that the routing is not set properly.

See attached screen capture :
https://github.com/geoffreybennett/alsa-scarlett-gui/assets/10098613/4462f055-94d1-457f-9be2-fa045d64e979

**Comment by fenugrec** [comment]
Another fun one : the PCM input level meters twitch around a bit but don't reflect the expected routing : (ignore the signal on mixer input 7, it just happened to be glitching there)

![pcm_inputs](https://github.com/geoffreybennett/alsa-scarlett-gui/assets/10098613/97b1e7db-5a59-47cf-bf50-3ab0f47c0540)

**Comment by geoffreybennett** [comment]
Hi @fenugrec,

Please see https://github.com/geoffreybennett/alsa-scarlett-gui/blob/master/INSTALL.md#prerequisites. You need 6.7 (or the driver from it) for the meters to work.

Instructions at https://github.com/geoffreybennett/scarlett-gen2/releases/tag/v6.5.11c1 for building just the snd-usb-audio as an update to your running kernel.

(yes, sorry, I did make a way to check from userspace if the meters are working, but have not implemented that in the GUI yet)

Regards,
Geoffrey.

**Comment by fenugrec** [comment]
I would've sworn the requirements said 6.6.  10/10 reading skills

**Comment by geoffreybennett** [comment]
Fixed in https://github.com/geoffreybennett/alsa-scarlett-gui/commit/befce0824fcebb86e49b9f45dc40b730c209b100.
