### ISSUE TITLE
Clarett 2Pre+ Either Input or Output working - not both

### ISSUE THREAD

**Issue by ydixken** [geoffreybennett/alsa-scarlett-gui#80]
Hi there,

first off - thank you for your work, amazing to see my Clarett working (again). Compiled 6.7 manually today and confirmed that the interface is recognized, but encounter a weird issue that either lets me use the input or output, but not both at once, the option dropdown within the sound settings basically resets. You can hear the "clicking" noise from the interface if you switch between sources.

OS: Ubuntu 23.10
Kernel: 6.7-rc2

Is there a recommended userspace configuration I need to use? Am I missing something.

Let me know if I can provide any logs.

**Comment by geoffreybennett** [comment]
Hi @ydixken,

Probably the profile is set input-only or output-only. I just installed Ubuntu 23.10 to check this and I see the same problem.

In pavucontrol, go to the configuration tab and select the Pro Audio profile. That should fix it.

Regards,
Geoffrey.

**Comment by ydixken** [comment]
I can confirm that this fixes it!

**Comment by geoffreybennett** [comment]
Awesome, thanks! Enjoy! :)
