### ISSUE TITLE
No S/PDIF input on 3rd gen 18i20

### ISSUE THREAD

**Issue by rekado** [geoffreybennett/alsa-scarlett-gui#90]
## Confirmation
- [X] I confirm that I have read the [FAQ](https://github.com/geoffreybennett/alsa-scarlett-gui/blob/master/FAQ.md).

## Issue Category
Please select the category that best describes your issue:
- [ ] Help Request
- [X] Bug Report
- [ ] Feature Request

## Environment Details
Please provide the following details about your environment.

### Linux Distribution and Version
(paste output from `cat /etc/redhat-release` or `cat /etc/lsb_release` here)
- Distribution: Guix System
- Version: commit: d1eac4f3b744737d5274efca40c0437e6246c9db

### Kernel Version
(paste output from `uname -r` here)
- Kernel version: 6.6.7 (same with 6.6.3)

### Kernel Messages
```
[   82.914294] usbcore: registered new interface driver snd-usb-audio
[   86.367971] usb 3-3: new high-speed USB device number 6 using xhci_hcd
[   86.517476] usb 3-3: New USB device found, idVendor=1235, idProduct=8215, bcdDevice= 6.0b
[   86.517505] usb 3-3: New USB device strings: Mfr=1, Product=3, SerialNumber=2
[   86.517515] usb 3-3: Product: Scarlett 18i20 USB
[   86.517522] usb 3-3: Manufacturer: Focusrite
[   86.517527] usb 3-3: SerialNumber: P9YY4773714C34
[   90.791226] usb 3-3: Focusrite Scarlett Gen 2/3 Mixer Driver enabled pid=0x8215
[   90.803386] usb 3-3: Quirk or no altest; falling back to MIDI 1.0
```

### Focusrite Interface Series and Model
(maybe shown in kernel messages, or paste output from `lsusb -d1235:` if unsure)
- Series: Scarlett 3rd Gen
- Model: 18i20

### Audio System
- [x] PulseAudio
- [ ] JACK
- [ ] PipeWire

## Issue Description

I have connected the S/PDIF output of my media center (an ARM computer) to the S/PDIF input of the Scarlett USB interface, using a coaxial cable.  The S/PDIF output of the USB interface is connected to the S/PDIF input of a Hifi amplifier.  The media center outputs music over its S/PDIF output.

In the Scarlett mixer (configured with alsa-scarlett-gui 0.3.3, and latest commit on `dev`) I routed both S/PDIF inputs directly to the S/PDIF outputs, hoping to achieve pass-through of the incoming signal, but there is no output.

I also tried routing the S/PDIF inputs to the internal mixer and connect the mixer outputs to the S/PDIF hardware outputs.  The incoming S/PDIF signal does not appear on the output.  Other channels routed through the mixer (such as a stereo instrument on channel 1 and 2) do however appear on the S/PDIF hardware outputs.

I do not know if the S/PDIF inputs on the USB interface successfully receive any signal as I don't know how to view the levels.  I noticed that when switching the clock from internal to S/PDIF the clock never switches to "locked" state.  I don't know if this is expected as I'm not using any studio clock signal.  My S/PDIF signal from the media center is just digital audio and it works with the Hifi amplifier's S/PDIF input.

I'd be happy to patch the kernel module or patch the code of also-scarlett-gui if necessary, or to provide any diagnostics.

(The Scarlett 18i20 is new, so I have no reason to assume that the S/PDIF hardware is broken.)

**Comment by geoffreybennett** [comment]
Hi @rekado,

My first thought is mismatched sample rates. For example, if PulseAudio is running at its default of 44.1kHz but your S/PDIF input is 48kHz, then it won't work. And when you switch the clock from internal to S/PDIF (as you should if you are using the S/PDIF input), it won't switch to the Locked state.

Likely your Hifi amp will accept either 44.1kHz or 48kHz and is switching automatically between them which is why outputs from both work, but your 18i20 will only be running at the rate PulseAudio has set, and that's not matching your media center.

Check `/proc/asound/card?/pcm0[cp]/hw_params` to see what sample rate you're using & check that they match.

Let me know how you go!

Thanks,
Geoffrey.

**Comment by rekado** [comment]
Hi Geoffrey,

you were right: after switching the pulseaudio default to 48kHz (same as what the media center uses) it all worked fine.
Thank you!
