### ISSUE TITLE
Open Sound Control support

### ISSUE THREAD

**Issue by Burtan** [geoffreybennett/alsa-scarlett-gui#92]
## Issue Category
- [ ] Help Request
- [ ] Bug Report
- [X] Feature Request

## Issue Description
Hey,
are you interested in adding OSC (Open Sound Control) support? RME e.g. offers it with TotalMixFX and it allows to control the mixer via tablets over wlan with supporting software (TouchOSC, OSCAR).

I might help with implementing it, although I'm mostly experienced with kotlin and not C++.

Thanks for consideration!

Disclaimer: I'm the developer of OSCAR, which I would provide a default template for if implemented here.

**Comment by geoffreybennett** [comment]
Hi @Burtan,

I'm not sure alsa-scarlett-gui is the right place to do this? The GUI is just a front-end to the ALSA mixer controls, and I presume that there's already an OSC interface for ALSA mixer controls?

Regards,
Geoffrey.

**Comment by Burtan** [comment]
I don't think there is an interface for ALSA mixer controls, yet, but you are probably right, that it is the better place for integration it.

**Comment by geoffreybennett** [comment]
That's surprising. I would think an ALSA mixer controls <-> OSC bridge would be a really useful thing.
